//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Data.EntityClient;
using System.ComponentModel;
using System.Xml.Serialization;
using System.Runtime.Serialization;

[assembly: EdmSchemaAttribute()]
#region EDM Relationship Metadata

[assembly: EdmRelationshipAttribute("EcoManagementModel", "FK_Classrooms_Buildings", "Buildings", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(EcoManagementServiceTester.Building), "Classrooms", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(EcoManagementServiceTester.Classroom), true)]
[assembly: EdmRelationshipAttribute("EcoManagementModel", "FK_Schedules_Classrooms", "Classrooms", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(EcoManagementServiceTester.Classroom), "Schedules", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(EcoManagementServiceTester.Schedule), true)]
[assembly: EdmRelationshipAttribute("EcoManagementModel", "FK_Workstations_Classrooms", "Classrooms", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(EcoManagementServiceTester.Classroom), "Workstations", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(EcoManagementServiceTester.Workstation), true)]
[assembly: EdmRelationshipAttribute("EcoManagementModel", "FK_Workstations_OperatingSystems", "OperatingSystems", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(EcoManagementServiceTester.OperatingSystem), "Workstations", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(EcoManagementServiceTester.Workstation), true)]
[assembly: EdmRelationshipAttribute("EcoManagementModel", "FK_Workstations_Whitelist", "Whitelist", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(EcoManagementServiceTester.Whitelist), "Workstations", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(EcoManagementServiceTester.Workstation), true)]
[assembly: EdmRelationshipAttribute("EcoManagementModel", "UserHasRoles", "Roles", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(EcoManagementServiceTester.Role), "Users", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(EcoManagementServiceTester.User))]

#endregion

namespace EcoManagementServiceTester
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class EcoManagementEntities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new EcoManagementEntities object using the connection string found in the 'EcoManagementEntities' section of the application configuration file.
        /// </summary>
        public EcoManagementEntities() : base("name=EcoManagementEntities", "EcoManagementEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new EcoManagementEntities object.
        /// </summary>
        public EcoManagementEntities(string connectionString) : base(connectionString, "EcoManagementEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new EcoManagementEntities object.
        /// </summary>
        public EcoManagementEntities(EntityConnection connection) : base(connection, "EcoManagementEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Building> Buildings
        {
            get
            {
                if ((_Buildings == null))
                {
                    _Buildings = base.CreateObjectSet<Building>("Buildings");
                }
                return _Buildings;
            }
        }
        private ObjectSet<Building> _Buildings;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Classroom> Classrooms
        {
            get
            {
                if ((_Classrooms == null))
                {
                    _Classrooms = base.CreateObjectSet<Classroom>("Classrooms");
                }
                return _Classrooms;
            }
        }
        private ObjectSet<Classroom> _Classrooms;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<OperatingSystem> OperatingSystems
        {
            get
            {
                if ((_OperatingSystems == null))
                {
                    _OperatingSystems = base.CreateObjectSet<OperatingSystem>("OperatingSystems");
                }
                return _OperatingSystems;
            }
        }
        private ObjectSet<OperatingSystem> _OperatingSystems;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Role> Roles
        {
            get
            {
                if ((_Roles == null))
                {
                    _Roles = base.CreateObjectSet<Role>("Roles");
                }
                return _Roles;
            }
        }
        private ObjectSet<Role> _Roles;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Schedule> Schedules
        {
            get
            {
                if ((_Schedules == null))
                {
                    _Schedules = base.CreateObjectSet<Schedule>("Schedules");
                }
                return _Schedules;
            }
        }
        private ObjectSet<Schedule> _Schedules;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<sysdiagram> sysdiagrams
        {
            get
            {
                if ((_sysdiagrams == null))
                {
                    _sysdiagrams = base.CreateObjectSet<sysdiagram>("sysdiagrams");
                }
                return _sysdiagrams;
            }
        }
        private ObjectSet<sysdiagram> _sysdiagrams;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<User> Users
        {
            get
            {
                if ((_Users == null))
                {
                    _Users = base.CreateObjectSet<User>("Users");
                }
                return _Users;
            }
        }
        private ObjectSet<User> _Users;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Whitelist> Whitelists
        {
            get
            {
                if ((_Whitelists == null))
                {
                    _Whitelists = base.CreateObjectSet<Whitelist>("Whitelists");
                }
                return _Whitelists;
            }
        }
        private ObjectSet<Whitelist> _Whitelists;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Workstation> Workstations
        {
            get
            {
                if ((_Workstations == null))
                {
                    _Workstations = base.CreateObjectSet<Workstation>("Workstations");
                }
                return _Workstations;
            }
        }
        private ObjectSet<Workstation> _Workstations;

        #endregion
        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Buildings EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToBuildings(Building building)
        {
            base.AddObject("Buildings", building);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Classrooms EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToClassrooms(Classroom classroom)
        {
            base.AddObject("Classrooms", classroom);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the OperatingSystems EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToOperatingSystems(OperatingSystem operatingSystem)
        {
            base.AddObject("OperatingSystems", operatingSystem);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Roles EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToRoles(Role role)
        {
            base.AddObject("Roles", role);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Schedules EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToSchedules(Schedule schedule)
        {
            base.AddObject("Schedules", schedule);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the sysdiagrams EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTosysdiagrams(sysdiagram sysdiagram)
        {
            base.AddObject("sysdiagrams", sysdiagram);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Users EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToUsers(User user)
        {
            base.AddObject("Users", user);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Whitelists EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToWhitelists(Whitelist whitelist)
        {
            base.AddObject("Whitelists", whitelist);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Workstations EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToWorkstations(Workstation workstation)
        {
            base.AddObject("Workstations", workstation);
        }

        #endregion
        #region Function Imports
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectResult<GetWorkstationsToBePoweredOFF_Result> GetWorkstationsToBePoweredOFF()
        {
            return base.ExecuteFunction<GetWorkstationsToBePoweredOFF_Result>("GetWorkstationsToBePoweredOFF");
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public int CleanWhitelist()
        {
            return base.ExecuteFunction("CleanWhitelist");
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectResult<GetWorkstationsToBePoweredON_Result> GetWorkstationsToBePoweredON()
        {
            return base.ExecuteFunction<GetWorkstationsToBePoweredON_Result>("GetWorkstationsToBePoweredON");
        }

        #endregion
    }
    

    #endregion
    
    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="EcoManagementModel", Name="Building")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Building : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Building object.
        /// </summary>
        /// <param name="id">Initial value of the ID property.</param>
        /// <param name="name">Initial value of the Name property.</param>
        /// <param name="isActive">Initial value of the IsActive property.</param>
        public static Building CreateBuilding(global::System.Int32 id, global::System.String name, global::System.Boolean isActive)
        {
            Building building = new Building();
            building.ID = id;
            building.Name = name;
            building.IsActive = isActive;
            return building;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ID
        {
            get
            {
                return _ID;
            }
            set
            {
                if (_ID != value)
                {
                    OnIDChanging(value);
                    ReportPropertyChanging("ID");
                    _ID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ID");
                    OnIDChanged();
                }
            }
        }
        private global::System.Int32 _ID;
        partial void OnIDChanging(global::System.Int32 value);
        partial void OnIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Name
        {
            get
            {
                return _Name;
            }
            set
            {
                OnNameChanging(value);
                ReportPropertyChanging("Name");
                _Name = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Name");
                OnNameChanged();
            }
        }
        private global::System.String _Name;
        partial void OnNameChanging(global::System.String value);
        partial void OnNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean IsActive
        {
            get
            {
                return _IsActive;
            }
            set
            {
                OnIsActiveChanging(value);
                ReportPropertyChanging("IsActive");
                _IsActive = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("IsActive");
                OnIsActiveChanged();
            }
        }
        private global::System.Boolean _IsActive;
        partial void OnIsActiveChanging(global::System.Boolean value);
        partial void OnIsActiveChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("EcoManagementModel", "FK_Classrooms_Buildings", "Classrooms")]
        public EntityCollection<Classroom> Classrooms
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Classroom>("EcoManagementModel.FK_Classrooms_Buildings", "Classrooms");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Classroom>("EcoManagementModel.FK_Classrooms_Buildings", "Classrooms", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="EcoManagementModel", Name="Classroom")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Classroom : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Classroom object.
        /// </summary>
        /// <param name="id">Initial value of the ID property.</param>
        /// <param name="name">Initial value of the Name property.</param>
        /// <param name="buildingID">Initial value of the BuildingID property.</param>
        /// <param name="isActive">Initial value of the IsActive property.</param>
        public static Classroom CreateClassroom(global::System.Int32 id, global::System.String name, global::System.Int32 buildingID, global::System.Boolean isActive)
        {
            Classroom classroom = new Classroom();
            classroom.ID = id;
            classroom.Name = name;
            classroom.BuildingID = buildingID;
            classroom.IsActive = isActive;
            return classroom;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ID
        {
            get
            {
                return _ID;
            }
            set
            {
                if (_ID != value)
                {
                    OnIDChanging(value);
                    ReportPropertyChanging("ID");
                    _ID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ID");
                    OnIDChanged();
                }
            }
        }
        private global::System.Int32 _ID;
        partial void OnIDChanging(global::System.Int32 value);
        partial void OnIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Name
        {
            get
            {
                return _Name;
            }
            set
            {
                OnNameChanging(value);
                ReportPropertyChanging("Name");
                _Name = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Name");
                OnNameChanged();
            }
        }
        private global::System.String _Name;
        partial void OnNameChanging(global::System.String value);
        partial void OnNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 BuildingID
        {
            get
            {
                return _BuildingID;
            }
            set
            {
                OnBuildingIDChanging(value);
                ReportPropertyChanging("BuildingID");
                _BuildingID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("BuildingID");
                OnBuildingIDChanged();
            }
        }
        private global::System.Int32 _BuildingID;
        partial void OnBuildingIDChanging(global::System.Int32 value);
        partial void OnBuildingIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean IsActive
        {
            get
            {
                return _IsActive;
            }
            set
            {
                OnIsActiveChanging(value);
                ReportPropertyChanging("IsActive");
                _IsActive = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("IsActive");
                OnIsActiveChanged();
            }
        }
        private global::System.Boolean _IsActive;
        partial void OnIsActiveChanging(global::System.Boolean value);
        partial void OnIsActiveChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("EcoManagementModel", "FK_Classrooms_Buildings", "Buildings")]
        public Building Building
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Building>("EcoManagementModel.FK_Classrooms_Buildings", "Buildings").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Building>("EcoManagementModel.FK_Classrooms_Buildings", "Buildings").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Building> BuildingReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Building>("EcoManagementModel.FK_Classrooms_Buildings", "Buildings");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Building>("EcoManagementModel.FK_Classrooms_Buildings", "Buildings", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("EcoManagementModel", "FK_Schedules_Classrooms", "Schedules")]
        public EntityCollection<Schedule> Schedules
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Schedule>("EcoManagementModel.FK_Schedules_Classrooms", "Schedules");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Schedule>("EcoManagementModel.FK_Schedules_Classrooms", "Schedules", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("EcoManagementModel", "FK_Workstations_Classrooms", "Workstations")]
        public EntityCollection<Workstation> Workstations
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Workstation>("EcoManagementModel.FK_Workstations_Classrooms", "Workstations");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Workstation>("EcoManagementModel.FK_Workstations_Classrooms", "Workstations", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="EcoManagementModel", Name="OperatingSystem")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class OperatingSystem : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new OperatingSystem object.
        /// </summary>
        /// <param name="id">Initial value of the ID property.</param>
        /// <param name="oSName">Initial value of the OSName property.</param>
        /// <param name="isActive">Initial value of the IsActive property.</param>
        public static OperatingSystem CreateOperatingSystem(global::System.Int32 id, global::System.String oSName, global::System.Boolean isActive)
        {
            OperatingSystem operatingSystem = new OperatingSystem();
            operatingSystem.ID = id;
            operatingSystem.OSName = oSName;
            operatingSystem.IsActive = isActive;
            return operatingSystem;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ID
        {
            get
            {
                return _ID;
            }
            set
            {
                if (_ID != value)
                {
                    OnIDChanging(value);
                    ReportPropertyChanging("ID");
                    _ID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ID");
                    OnIDChanged();
                }
            }
        }
        private global::System.Int32 _ID;
        partial void OnIDChanging(global::System.Int32 value);
        partial void OnIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String OSName
        {
            get
            {
                return _OSName;
            }
            set
            {
                OnOSNameChanging(value);
                ReportPropertyChanging("OSName");
                _OSName = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("OSName");
                OnOSNameChanged();
            }
        }
        private global::System.String _OSName;
        partial void OnOSNameChanging(global::System.String value);
        partial void OnOSNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean IsActive
        {
            get
            {
                return _IsActive;
            }
            set
            {
                OnIsActiveChanging(value);
                ReportPropertyChanging("IsActive");
                _IsActive = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("IsActive");
                OnIsActiveChanged();
            }
        }
        private global::System.Boolean _IsActive;
        partial void OnIsActiveChanging(global::System.Boolean value);
        partial void OnIsActiveChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("EcoManagementModel", "FK_Workstations_OperatingSystems", "Workstations")]
        public EntityCollection<Workstation> Workstations
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Workstation>("EcoManagementModel.FK_Workstations_OperatingSystems", "Workstations");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Workstation>("EcoManagementModel.FK_Workstations_OperatingSystems", "Workstations", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="EcoManagementModel", Name="Role")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Role : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Role object.
        /// </summary>
        /// <param name="id">Initial value of the ID property.</param>
        /// <param name="label">Initial value of the Label property.</param>
        /// <param name="description">Initial value of the Description property.</param>
        /// <param name="isActive">Initial value of the IsActive property.</param>
        public static Role CreateRole(global::System.Int32 id, global::System.String label, global::System.String description, global::System.Boolean isActive)
        {
            Role role = new Role();
            role.ID = id;
            role.Label = label;
            role.Description = description;
            role.IsActive = isActive;
            return role;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ID
        {
            get
            {
                return _ID;
            }
            set
            {
                if (_ID != value)
                {
                    OnIDChanging(value);
                    ReportPropertyChanging("ID");
                    _ID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ID");
                    OnIDChanged();
                }
            }
        }
        private global::System.Int32 _ID;
        partial void OnIDChanging(global::System.Int32 value);
        partial void OnIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Label
        {
            get
            {
                return _Label;
            }
            set
            {
                OnLabelChanging(value);
                ReportPropertyChanging("Label");
                _Label = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Label");
                OnLabelChanged();
            }
        }
        private global::System.String _Label;
        partial void OnLabelChanging(global::System.String value);
        partial void OnLabelChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Description
        {
            get
            {
                return _Description;
            }
            set
            {
                OnDescriptionChanging(value);
                ReportPropertyChanging("Description");
                _Description = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Description");
                OnDescriptionChanged();
            }
        }
        private global::System.String _Description;
        partial void OnDescriptionChanging(global::System.String value);
        partial void OnDescriptionChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean IsActive
        {
            get
            {
                return _IsActive;
            }
            set
            {
                OnIsActiveChanging(value);
                ReportPropertyChanging("IsActive");
                _IsActive = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("IsActive");
                OnIsActiveChanged();
            }
        }
        private global::System.Boolean _IsActive;
        partial void OnIsActiveChanging(global::System.Boolean value);
        partial void OnIsActiveChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("EcoManagementModel", "UserHasRoles", "Users")]
        public EntityCollection<User> Users
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<User>("EcoManagementModel.UserHasRoles", "Users");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<User>("EcoManagementModel.UserHasRoles", "Users", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="EcoManagementModel", Name="Schedule")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Schedule : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Schedule object.
        /// </summary>
        /// <param name="id">Initial value of the ID property.</param>
        /// <param name="powerOn">Initial value of the PowerOn property.</param>
        /// <param name="powerDown">Initial value of the PowerDown property.</param>
        /// <param name="dayOfTheWeek">Initial value of the DayOfTheWeek property.</param>
        /// <param name="reason">Initial value of the Reason property.</param>
        /// <param name="classroomID">Initial value of the ClassroomID property.</param>
        /// <param name="isActive">Initial value of the IsActive property.</param>
        public static Schedule CreateSchedule(global::System.Int32 id, global::System.DateTime powerOn, global::System.DateTime powerDown, global::System.String dayOfTheWeek, global::System.String reason, global::System.Int32 classroomID, global::System.Boolean isActive)
        {
            Schedule schedule = new Schedule();
            schedule.ID = id;
            schedule.PowerOn = powerOn;
            schedule.PowerDown = powerDown;
            schedule.DayOfTheWeek = dayOfTheWeek;
            schedule.Reason = reason;
            schedule.ClassroomID = classroomID;
            schedule.IsActive = isActive;
            return schedule;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ID
        {
            get
            {
                return _ID;
            }
            set
            {
                if (_ID != value)
                {
                    OnIDChanging(value);
                    ReportPropertyChanging("ID");
                    _ID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ID");
                    OnIDChanged();
                }
            }
        }
        private global::System.Int32 _ID;
        partial void OnIDChanging(global::System.Int32 value);
        partial void OnIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime PowerOn
        {
            get
            {
                return _PowerOn;
            }
            set
            {
                OnPowerOnChanging(value);
                ReportPropertyChanging("PowerOn");
                _PowerOn = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("PowerOn");
                OnPowerOnChanged();
            }
        }
        private global::System.DateTime _PowerOn;
        partial void OnPowerOnChanging(global::System.DateTime value);
        partial void OnPowerOnChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime PowerDown
        {
            get
            {
                return _PowerDown;
            }
            set
            {
                OnPowerDownChanging(value);
                ReportPropertyChanging("PowerDown");
                _PowerDown = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("PowerDown");
                OnPowerDownChanged();
            }
        }
        private global::System.DateTime _PowerDown;
        partial void OnPowerDownChanging(global::System.DateTime value);
        partial void OnPowerDownChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String DayOfTheWeek
        {
            get
            {
                return _DayOfTheWeek;
            }
            set
            {
                OnDayOfTheWeekChanging(value);
                ReportPropertyChanging("DayOfTheWeek");
                _DayOfTheWeek = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("DayOfTheWeek");
                OnDayOfTheWeekChanged();
            }
        }
        private global::System.String _DayOfTheWeek;
        partial void OnDayOfTheWeekChanging(global::System.String value);
        partial void OnDayOfTheWeekChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Reason
        {
            get
            {
                return _Reason;
            }
            set
            {
                OnReasonChanging(value);
                ReportPropertyChanging("Reason");
                _Reason = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Reason");
                OnReasonChanged();
            }
        }
        private global::System.String _Reason;
        partial void OnReasonChanging(global::System.String value);
        partial void OnReasonChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ClassroomID
        {
            get
            {
                return _ClassroomID;
            }
            set
            {
                OnClassroomIDChanging(value);
                ReportPropertyChanging("ClassroomID");
                _ClassroomID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ClassroomID");
                OnClassroomIDChanged();
            }
        }
        private global::System.Int32 _ClassroomID;
        partial void OnClassroomIDChanging(global::System.Int32 value);
        partial void OnClassroomIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean IsActive
        {
            get
            {
                return _IsActive;
            }
            set
            {
                OnIsActiveChanging(value);
                ReportPropertyChanging("IsActive");
                _IsActive = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("IsActive");
                OnIsActiveChanged();
            }
        }
        private global::System.Boolean _IsActive;
        partial void OnIsActiveChanging(global::System.Boolean value);
        partial void OnIsActiveChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("EcoManagementModel", "FK_Schedules_Classrooms", "Classrooms")]
        public Classroom Classroom
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Classroom>("EcoManagementModel.FK_Schedules_Classrooms", "Classrooms").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Classroom>("EcoManagementModel.FK_Schedules_Classrooms", "Classrooms").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Classroom> ClassroomReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Classroom>("EcoManagementModel.FK_Schedules_Classrooms", "Classrooms");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Classroom>("EcoManagementModel.FK_Schedules_Classrooms", "Classrooms", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="EcoManagementModel", Name="sysdiagram")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class sysdiagram : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new sysdiagram object.
        /// </summary>
        /// <param name="name">Initial value of the name property.</param>
        /// <param name="principal_id">Initial value of the principal_id property.</param>
        /// <param name="diagram_id">Initial value of the diagram_id property.</param>
        public static sysdiagram Createsysdiagram(global::System.String name, global::System.Int32 principal_id, global::System.Int32 diagram_id)
        {
            sysdiagram sysdiagram = new sysdiagram();
            sysdiagram.name = name;
            sysdiagram.principal_id = principal_id;
            sysdiagram.diagram_id = diagram_id;
            return sysdiagram;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String name
        {
            get
            {
                return _name;
            }
            set
            {
                OnnameChanging(value);
                ReportPropertyChanging("name");
                _name = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("name");
                OnnameChanged();
            }
        }
        private global::System.String _name;
        partial void OnnameChanging(global::System.String value);
        partial void OnnameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 principal_id
        {
            get
            {
                return _principal_id;
            }
            set
            {
                Onprincipal_idChanging(value);
                ReportPropertyChanging("principal_id");
                _principal_id = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("principal_id");
                Onprincipal_idChanged();
            }
        }
        private global::System.Int32 _principal_id;
        partial void Onprincipal_idChanging(global::System.Int32 value);
        partial void Onprincipal_idChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 diagram_id
        {
            get
            {
                return _diagram_id;
            }
            set
            {
                if (_diagram_id != value)
                {
                    Ondiagram_idChanging(value);
                    ReportPropertyChanging("diagram_id");
                    _diagram_id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("diagram_id");
                    Ondiagram_idChanged();
                }
            }
        }
        private global::System.Int32 _diagram_id;
        partial void Ondiagram_idChanging(global::System.Int32 value);
        partial void Ondiagram_idChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> version
        {
            get
            {
                return _version;
            }
            set
            {
                OnversionChanging(value);
                ReportPropertyChanging("version");
                _version = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("version");
                OnversionChanged();
            }
        }
        private Nullable<global::System.Int32> _version;
        partial void OnversionChanging(Nullable<global::System.Int32> value);
        partial void OnversionChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.Byte[] definition
        {
            get
            {
                return StructuralObject.GetValidValue(_definition);
            }
            set
            {
                OndefinitionChanging(value);
                ReportPropertyChanging("definition");
                _definition = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("definition");
                OndefinitionChanged();
            }
        }
        private global::System.Byte[] _definition;
        partial void OndefinitionChanging(global::System.Byte[] value);
        partial void OndefinitionChanged();

        #endregion
    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="EcoManagementModel", Name="User")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class User : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new User object.
        /// </summary>
        /// <param name="id">Initial value of the ID property.</param>
        /// <param name="userName">Initial value of the UserName property.</param>
        /// <param name="password">Initial value of the Password property.</param>
        /// <param name="roleID">Initial value of the RoleID property.</param>
        /// <param name="isActive">Initial value of the IsActive property.</param>
        public static User CreateUser(global::System.Int32 id, global::System.String userName, global::System.String password, global::System.Int32 roleID, global::System.Boolean isActive)
        {
            User user = new User();
            user.ID = id;
            user.UserName = userName;
            user.Password = password;
            user.RoleID = roleID;
            user.IsActive = isActive;
            return user;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ID
        {
            get
            {
                return _ID;
            }
            set
            {
                if (_ID != value)
                {
                    OnIDChanging(value);
                    ReportPropertyChanging("ID");
                    _ID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ID");
                    OnIDChanged();
                }
            }
        }
        private global::System.Int32 _ID;
        partial void OnIDChanging(global::System.Int32 value);
        partial void OnIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String UserName
        {
            get
            {
                return _UserName;
            }
            set
            {
                OnUserNameChanging(value);
                ReportPropertyChanging("UserName");
                _UserName = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("UserName");
                OnUserNameChanged();
            }
        }
        private global::System.String _UserName;
        partial void OnUserNameChanging(global::System.String value);
        partial void OnUserNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Password
        {
            get
            {
                return _Password;
            }
            set
            {
                OnPasswordChanging(value);
                ReportPropertyChanging("Password");
                _Password = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Password");
                OnPasswordChanged();
            }
        }
        private global::System.String _Password;
        partial void OnPasswordChanging(global::System.String value);
        partial void OnPasswordChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 RoleID
        {
            get
            {
                return _RoleID;
            }
            set
            {
                OnRoleIDChanging(value);
                ReportPropertyChanging("RoleID");
                _RoleID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("RoleID");
                OnRoleIDChanged();
            }
        }
        private global::System.Int32 _RoleID;
        partial void OnRoleIDChanging(global::System.Int32 value);
        partial void OnRoleIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean IsActive
        {
            get
            {
                return _IsActive;
            }
            set
            {
                OnIsActiveChanging(value);
                ReportPropertyChanging("IsActive");
                _IsActive = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("IsActive");
                OnIsActiveChanged();
            }
        }
        private global::System.Boolean _IsActive;
        partial void OnIsActiveChanging(global::System.Boolean value);
        partial void OnIsActiveChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("EcoManagementModel", "UserHasRoles", "Roles")]
        public EntityCollection<Role> Roles
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Role>("EcoManagementModel.UserHasRoles", "Roles");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Role>("EcoManagementModel.UserHasRoles", "Roles", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="EcoManagementModel", Name="Whitelist")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Whitelist : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Whitelist object.
        /// </summary>
        /// <param name="id">Initial value of the ID property.</param>
        /// <param name="start">Initial value of the Start property.</param>
        /// <param name="end">Initial value of the End property.</param>
        /// <param name="reason">Initial value of the Reason property.</param>
        /// <param name="createdBy">Initial value of the CreatedBy property.</param>
        /// <param name="isActive">Initial value of the IsActive property.</param>
        public static Whitelist CreateWhitelist(global::System.Int32 id, global::System.DateTime start, global::System.DateTime end, global::System.String reason, global::System.Int32 createdBy, global::System.Boolean isActive)
        {
            Whitelist whitelist = new Whitelist();
            whitelist.ID = id;
            whitelist.Start = start;
            whitelist.End = end;
            whitelist.Reason = reason;
            whitelist.CreatedBy = createdBy;
            whitelist.IsActive = isActive;
            return whitelist;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ID
        {
            get
            {
                return _ID;
            }
            set
            {
                if (_ID != value)
                {
                    OnIDChanging(value);
                    ReportPropertyChanging("ID");
                    _ID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ID");
                    OnIDChanged();
                }
            }
        }
        private global::System.Int32 _ID;
        partial void OnIDChanging(global::System.Int32 value);
        partial void OnIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime Start
        {
            get
            {
                return _Start;
            }
            set
            {
                OnStartChanging(value);
                ReportPropertyChanging("Start");
                _Start = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Start");
                OnStartChanged();
            }
        }
        private global::System.DateTime _Start;
        partial void OnStartChanging(global::System.DateTime value);
        partial void OnStartChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime End
        {
            get
            {
                return _End;
            }
            set
            {
                OnEndChanging(value);
                ReportPropertyChanging("End");
                _End = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("End");
                OnEndChanged();
            }
        }
        private global::System.DateTime _End;
        partial void OnEndChanging(global::System.DateTime value);
        partial void OnEndChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Reason
        {
            get
            {
                return _Reason;
            }
            set
            {
                OnReasonChanging(value);
                ReportPropertyChanging("Reason");
                _Reason = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Reason");
                OnReasonChanged();
            }
        }
        private global::System.String _Reason;
        partial void OnReasonChanging(global::System.String value);
        partial void OnReasonChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 CreatedBy
        {
            get
            {
                return _CreatedBy;
            }
            set
            {
                OnCreatedByChanging(value);
                ReportPropertyChanging("CreatedBy");
                _CreatedBy = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("CreatedBy");
                OnCreatedByChanged();
            }
        }
        private global::System.Int32 _CreatedBy;
        partial void OnCreatedByChanging(global::System.Int32 value);
        partial void OnCreatedByChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean IsActive
        {
            get
            {
                return _IsActive;
            }
            set
            {
                OnIsActiveChanging(value);
                ReportPropertyChanging("IsActive");
                _IsActive = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("IsActive");
                OnIsActiveChanged();
            }
        }
        private global::System.Boolean _IsActive;
        partial void OnIsActiveChanging(global::System.Boolean value);
        partial void OnIsActiveChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("EcoManagementModel", "FK_Workstations_Whitelist", "Workstations")]
        public EntityCollection<Workstation> Workstations
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Workstation>("EcoManagementModel.FK_Workstations_Whitelist", "Workstations");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Workstation>("EcoManagementModel.FK_Workstations_Whitelist", "Workstations", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="EcoManagementModel", Name="Workstation")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Workstation : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Workstation object.
        /// </summary>
        /// <param name="id">Initial value of the ID property.</param>
        /// <param name="name">Initial value of the Name property.</param>
        /// <param name="mAC_Address">Initial value of the MAC_Address property.</param>
        /// <param name="classroomID">Initial value of the ClassroomID property.</param>
        /// <param name="admin">Initial value of the Admin property.</param>
        /// <param name="isActive">Initial value of the IsActive property.</param>
        /// <param name="oSID">Initial value of the OSID property.</param>
        public static Workstation CreateWorkstation(global::System.Int32 id, global::System.String name, global::System.String mAC_Address, global::System.Int32 classroomID, global::System.Int32 admin, global::System.Boolean isActive, global::System.Int32 oSID)
        {
            Workstation workstation = new Workstation();
            workstation.ID = id;
            workstation.Name = name;
            workstation.MAC_Address = mAC_Address;
            workstation.ClassroomID = classroomID;
            workstation.Admin = admin;
            workstation.IsActive = isActive;
            workstation.OSID = oSID;
            return workstation;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ID
        {
            get
            {
                return _ID;
            }
            set
            {
                if (_ID != value)
                {
                    OnIDChanging(value);
                    ReportPropertyChanging("ID");
                    _ID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ID");
                    OnIDChanged();
                }
            }
        }
        private global::System.Int32 _ID;
        partial void OnIDChanging(global::System.Int32 value);
        partial void OnIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Name
        {
            get
            {
                return _Name;
            }
            set
            {
                OnNameChanging(value);
                ReportPropertyChanging("Name");
                _Name = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Name");
                OnNameChanged();
            }
        }
        private global::System.String _Name;
        partial void OnNameChanging(global::System.String value);
        partial void OnNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String MAC_Address
        {
            get
            {
                return _MAC_Address;
            }
            set
            {
                OnMAC_AddressChanging(value);
                ReportPropertyChanging("MAC_Address");
                _MAC_Address = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("MAC_Address");
                OnMAC_AddressChanged();
            }
        }
        private global::System.String _MAC_Address;
        partial void OnMAC_AddressChanging(global::System.String value);
        partial void OnMAC_AddressChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ClassroomID
        {
            get
            {
                return _ClassroomID;
            }
            set
            {
                OnClassroomIDChanging(value);
                ReportPropertyChanging("ClassroomID");
                _ClassroomID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ClassroomID");
                OnClassroomIDChanged();
            }
        }
        private global::System.Int32 _ClassroomID;
        partial void OnClassroomIDChanging(global::System.Int32 value);
        partial void OnClassroomIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Admin
        {
            get
            {
                return _Admin;
            }
            set
            {
                OnAdminChanging(value);
                ReportPropertyChanging("Admin");
                _Admin = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Admin");
                OnAdminChanged();
            }
        }
        private global::System.Int32 _Admin;
        partial void OnAdminChanging(global::System.Int32 value);
        partial void OnAdminChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean IsActive
        {
            get
            {
                return _IsActive;
            }
            set
            {
                OnIsActiveChanging(value);
                ReportPropertyChanging("IsActive");
                _IsActive = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("IsActive");
                OnIsActiveChanged();
            }
        }
        private global::System.Boolean _IsActive;
        partial void OnIsActiveChanging(global::System.Boolean value);
        partial void OnIsActiveChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> WhitelistID
        {
            get
            {
                return _WhitelistID;
            }
            set
            {
                OnWhitelistIDChanging(value);
                ReportPropertyChanging("WhitelistID");
                _WhitelistID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("WhitelistID");
                OnWhitelistIDChanged();
            }
        }
        private Nullable<global::System.Int32> _WhitelistID;
        partial void OnWhitelistIDChanging(Nullable<global::System.Int32> value);
        partial void OnWhitelistIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 OSID
        {
            get
            {
                return _OSID;
            }
            set
            {
                OnOSIDChanging(value);
                ReportPropertyChanging("OSID");
                _OSID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("OSID");
                OnOSIDChanged();
            }
        }
        private global::System.Int32 _OSID;
        partial void OnOSIDChanging(global::System.Int32 value);
        partial void OnOSIDChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("EcoManagementModel", "FK_Workstations_Classrooms", "Classrooms")]
        public Classroom Classroom
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Classroom>("EcoManagementModel.FK_Workstations_Classrooms", "Classrooms").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Classroom>("EcoManagementModel.FK_Workstations_Classrooms", "Classrooms").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Classroom> ClassroomReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Classroom>("EcoManagementModel.FK_Workstations_Classrooms", "Classrooms");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Classroom>("EcoManagementModel.FK_Workstations_Classrooms", "Classrooms", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("EcoManagementModel", "FK_Workstations_OperatingSystems", "OperatingSystems")]
        public OperatingSystem OperatingSystem
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<OperatingSystem>("EcoManagementModel.FK_Workstations_OperatingSystems", "OperatingSystems").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<OperatingSystem>("EcoManagementModel.FK_Workstations_OperatingSystems", "OperatingSystems").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<OperatingSystem> OperatingSystemReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<OperatingSystem>("EcoManagementModel.FK_Workstations_OperatingSystems", "OperatingSystems");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<OperatingSystem>("EcoManagementModel.FK_Workstations_OperatingSystems", "OperatingSystems", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("EcoManagementModel", "FK_Workstations_Whitelist", "Whitelist")]
        public Whitelist Whitelist
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Whitelist>("EcoManagementModel.FK_Workstations_Whitelist", "Whitelist").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Whitelist>("EcoManagementModel.FK_Workstations_Whitelist", "Whitelist").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Whitelist> WhitelistReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Whitelist>("EcoManagementModel.FK_Workstations_Whitelist", "Whitelist");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Whitelist>("EcoManagementModel.FK_Workstations_Whitelist", "Whitelist", value);
                }
            }
        }

        #endregion
    }

    #endregion
    #region ComplexTypes
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmComplexTypeAttribute(NamespaceName="EcoManagementModel", Name="GetWorkstationsToBePoweredOFF_Result")]
    [DataContractAttribute(IsReference=true)]
    [Serializable()]
    public partial class GetWorkstationsToBePoweredOFF_Result : ComplexObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new GetWorkstationsToBePoweredOFF_Result object.
        /// </summary>
        /// <param name="name">Initial value of the Name property.</param>
        /// <param name="mAC_Address">Initial value of the MAC_Address property.</param>
        /// <param name="oSName">Initial value of the OSName property.</param>
        /// <param name="classroomID">Initial value of the ClassroomID property.</param>
        public static GetWorkstationsToBePoweredOFF_Result CreateGetWorkstationsToBePoweredOFF_Result(global::System.String name, global::System.String mAC_Address, global::System.String oSName, global::System.Int32 classroomID)
        {
            GetWorkstationsToBePoweredOFF_Result getWorkstationsToBePoweredOFF_Result = new GetWorkstationsToBePoweredOFF_Result();
            getWorkstationsToBePoweredOFF_Result.Name = name;
            getWorkstationsToBePoweredOFF_Result.MAC_Address = mAC_Address;
            getWorkstationsToBePoweredOFF_Result.OSName = oSName;
            getWorkstationsToBePoweredOFF_Result.ClassroomID = classroomID;
            return getWorkstationsToBePoweredOFF_Result;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Name
        {
            get
            {
                return _Name;
            }
            set
            {
                OnNameChanging(value);
                ReportPropertyChanging("Name");
                _Name = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Name");
                OnNameChanged();
            }
        }
        private global::System.String _Name;
        partial void OnNameChanging(global::System.String value);
        partial void OnNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String MAC_Address
        {
            get
            {
                return _MAC_Address;
            }
            set
            {
                OnMAC_AddressChanging(value);
                ReportPropertyChanging("MAC_Address");
                _MAC_Address = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("MAC_Address");
                OnMAC_AddressChanged();
            }
        }
        private global::System.String _MAC_Address;
        partial void OnMAC_AddressChanging(global::System.String value);
        partial void OnMAC_AddressChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String OSName
        {
            get
            {
                return _OSName;
            }
            set
            {
                OnOSNameChanging(value);
                ReportPropertyChanging("OSName");
                _OSName = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("OSName");
                OnOSNameChanged();
            }
        }
        private global::System.String _OSName;
        partial void OnOSNameChanging(global::System.String value);
        partial void OnOSNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ClassroomID
        {
            get
            {
                return _ClassroomID;
            }
            set
            {
                OnClassroomIDChanging(value);
                ReportPropertyChanging("ClassroomID");
                _ClassroomID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ClassroomID");
                OnClassroomIDChanged();
            }
        }
        private global::System.Int32 _ClassroomID;
        partial void OnClassroomIDChanging(global::System.Int32 value);
        partial void OnClassroomIDChanged();

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmComplexTypeAttribute(NamespaceName="EcoManagementModel", Name="GetWorkstationsToBePoweredON_Result")]
    [DataContractAttribute(IsReference=true)]
    [Serializable()]
    public partial class GetWorkstationsToBePoweredON_Result : ComplexObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new GetWorkstationsToBePoweredON_Result object.
        /// </summary>
        /// <param name="name">Initial value of the Name property.</param>
        /// <param name="mAC_Address">Initial value of the MAC_Address property.</param>
        /// <param name="oSName">Initial value of the OSName property.</param>
        /// <param name="classroomID">Initial value of the ClassroomID property.</param>
        public static GetWorkstationsToBePoweredON_Result CreateGetWorkstationsToBePoweredON_Result(global::System.String name, global::System.String mAC_Address, global::System.String oSName, global::System.Int32 classroomID)
        {
            GetWorkstationsToBePoweredON_Result getWorkstationsToBePoweredON_Result = new GetWorkstationsToBePoweredON_Result();
            getWorkstationsToBePoweredON_Result.Name = name;
            getWorkstationsToBePoweredON_Result.MAC_Address = mAC_Address;
            getWorkstationsToBePoweredON_Result.OSName = oSName;
            getWorkstationsToBePoweredON_Result.ClassroomID = classroomID;
            return getWorkstationsToBePoweredON_Result;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Name
        {
            get
            {
                return _Name;
            }
            set
            {
                OnNameChanging(value);
                ReportPropertyChanging("Name");
                _Name = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Name");
                OnNameChanged();
            }
        }
        private global::System.String _Name;
        partial void OnNameChanging(global::System.String value);
        partial void OnNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String MAC_Address
        {
            get
            {
                return _MAC_Address;
            }
            set
            {
                OnMAC_AddressChanging(value);
                ReportPropertyChanging("MAC_Address");
                _MAC_Address = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("MAC_Address");
                OnMAC_AddressChanged();
            }
        }
        private global::System.String _MAC_Address;
        partial void OnMAC_AddressChanging(global::System.String value);
        partial void OnMAC_AddressChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String OSName
        {
            get
            {
                return _OSName;
            }
            set
            {
                OnOSNameChanging(value);
                ReportPropertyChanging("OSName");
                _OSName = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("OSName");
                OnOSNameChanged();
            }
        }
        private global::System.String _OSName;
        partial void OnOSNameChanging(global::System.String value);
        partial void OnOSNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ClassroomID
        {
            get
            {
                return _ClassroomID;
            }
            set
            {
                OnClassroomIDChanging(value);
                ReportPropertyChanging("ClassroomID");
                _ClassroomID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ClassroomID");
                OnClassroomIDChanged();
            }
        }
        private global::System.Int32 _ClassroomID;
        partial void OnClassroomIDChanging(global::System.Int32 value);
        partial void OnClassroomIDChanged();

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmComplexTypeAttribute(NamespaceName="EcoManagementModel", Name="sp_GetWorkstationsToBePoweredON_Result")]
    [DataContractAttribute(IsReference=true)]
    [Serializable()]
    public partial class sp_GetWorkstationsToBePoweredON_Result : ComplexObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new sp_GetWorkstationsToBePoweredON_Result object.
        /// </summary>
        /// <param name="name">Initial value of the Name property.</param>
        /// <param name="mAC_Address">Initial value of the MAC_Address property.</param>
        /// <param name="oSName">Initial value of the OSName property.</param>
        /// <param name="classroomID">Initial value of the ClassroomID property.</param>
        public static sp_GetWorkstationsToBePoweredON_Result Createsp_GetWorkstationsToBePoweredON_Result(global::System.String name, global::System.String mAC_Address, global::System.String oSName, global::System.Int32 classroomID)
        {
            sp_GetWorkstationsToBePoweredON_Result sp_GetWorkstationsToBePoweredON_Result = new sp_GetWorkstationsToBePoweredON_Result();
            sp_GetWorkstationsToBePoweredON_Result.Name = name;
            sp_GetWorkstationsToBePoweredON_Result.MAC_Address = mAC_Address;
            sp_GetWorkstationsToBePoweredON_Result.OSName = oSName;
            sp_GetWorkstationsToBePoweredON_Result.ClassroomID = classroomID;
            return sp_GetWorkstationsToBePoweredON_Result;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Name
        {
            get
            {
                return _Name;
            }
            set
            {
                OnNameChanging(value);
                ReportPropertyChanging("Name");
                _Name = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Name");
                OnNameChanged();
            }
        }
        private global::System.String _Name;
        partial void OnNameChanging(global::System.String value);
        partial void OnNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String MAC_Address
        {
            get
            {
                return _MAC_Address;
            }
            set
            {
                OnMAC_AddressChanging(value);
                ReportPropertyChanging("MAC_Address");
                _MAC_Address = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("MAC_Address");
                OnMAC_AddressChanged();
            }
        }
        private global::System.String _MAC_Address;
        partial void OnMAC_AddressChanging(global::System.String value);
        partial void OnMAC_AddressChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String OSName
        {
            get
            {
                return _OSName;
            }
            set
            {
                OnOSNameChanging(value);
                ReportPropertyChanging("OSName");
                _OSName = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("OSName");
                OnOSNameChanged();
            }
        }
        private global::System.String _OSName;
        partial void OnOSNameChanging(global::System.String value);
        partial void OnOSNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ClassroomID
        {
            get
            {
                return _ClassroomID;
            }
            set
            {
                OnClassroomIDChanging(value);
                ReportPropertyChanging("ClassroomID");
                _ClassroomID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ClassroomID");
                OnClassroomIDChanged();
            }
        }
        private global::System.Int32 _ClassroomID;
        partial void OnClassroomIDChanging(global::System.Int32 value);
        partial void OnClassroomIDChanged();

        #endregion
    }

    #endregion
    
}
